name: cd-python-tcc
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - pandas
  - python-dateutil
  - matplotlib
  - ipython
  - plotly
  - pystan
  - prophet
  - scikit-learn
  - scipy
  - seaborn